Fixed the issue of variable in insert "out of scope of match query" in update query
vaticle/typedb pull request #6823
Opened 2023-06-14 14:51 UTC by shiladitya-mukherjee

## What is the goal of this PR?
The issue was raised [here](https://github.com/vaticle/typedb/issues/6549). The goal of this PR is to resolve this issue.
This issue provided a fundamental limitation in TypeQL queries: one could not insert entities in update queries. This is because inserting a new entity would require the presence of a unbounded variable present only in the `insert` part of the Update query, and due to a bug, the `insert` query could not have named variables not in scope of a `match` query. 
Now, the changes allow one to insert new independent variables in the `insert` part of the Update query

## What are the changes implemented in this PR?

For the `get` output of the `match` query that subsequently feeds into delete and insert, the variables we need are the intersection of the `insert` and the `match` query. The set of variables in the `delete` query should be a subset of the set of variables in `match` query.

So, using `retainAll`, we perform set intersection between `insert` and `match` query variables, and then add all the variables of the delete query. The `filtersAreInScope()` function in the TypeQL repository will take care of the check with `delete` variables being a subset of the `match` variables.

2023-06-14 21:59 UTC, krishnangovindraj requested changes
Please add the typedb repository to your factory settings so CI will run.

We can also restructure the PR description to be more concise. But overall, looks good :)

2023-06-14 21:59 UTC, krishnangovindraj commented on query/Updater.java
> +            HashSet<UnboundVariable> filter = new HashSet<>(query.match().namedVariablesUnbound());
Try not to add new lines if they're not needed (so they mean something when we use them where they are needed)

2023-06-15 09:42 UTC, krishnangovindraj approved these changes
Looks good to me.

2023-06-15 09:45 UTC, benjaminasmall approved these changes
@krishnangovindraj says good.

2023-06-15 10:16 UTC, flyingsilverfin approved these changes

2023-06-15 10:41 UTC, merged