Validation for programmatic schema migration
vaticle/typedb pull request #6981
Opened 2024-02-06 17:13 UTC by krishnangovindraj

## Usage and product changes
Introduces extensive validation against schema modifications.
See  

## Implementation

2024-02-08 11:50 UTC, krishnangovindraj reviewed
self review

2024-02-08 11:50 UTC, krishnangovindraj commented on concept/type/impl/RoleTypeImpl.java
> -    }
Again, moved validation to unset relates. The other option is to move the validation to delete here & for owns.

2024-02-08 11:50 UTC, krishnangovindraj commented on concept/type/impl/ThingTypeImpl.java
> +                validateOwnsAreNotRedeclared()
Should we move the implementation of all these methods to `SchemaValidation`?

2024-02-09 11:30 UTC, flyingsilverfin requested changes

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/validation/SchemaValidation.java
> +        private static void validateNoBrokenOverrides(RelationType relationType, Set<RoleType> removed, List<TypeDBException> acc) {
Overriddes should all be validated at "commit" time

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/validation/SchemaValidation.java
> +                        overriddenHere.add(roleType);
Same bug here

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/validation/SchemaValidation.java
> +        private static void validateNoLeakedInstances(RelationType relationType, Set<RoleType> removedOrHidden, List<TypeDBException> acc) {
```
validateInstances(RelationType relationType, Set<RoleType> noLongerInherited, List<TypeDBException> exceptions)
```

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/validation/SchemaValidation.java
> +        private static void validateNoBrokenOverrides(RelationType relationType, Set<RoleType> removed, List<TypeDBException> acc) {
```
validateOverrides(RelationType relationType, Set<RoleType> noLongerInherited, List<TypeDBException> exceptions)
```

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/validation/SchemaValidation.java
> +        public static List<TypeDBException> validateAdd(ThingType thingType, RoleType added, @Nullable RoleType overridden) {
rename:
1. ValidateOverride(overridden)

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/type/impl/AttributeTypeImpl.java
> +        SchemaValidation.throwIfNonEmpty(Iterators.link(
Let's split the stuff above here into `validateDeclaration`-type methods, so we have some symmetry with `SubtypeValidation`.

2024-02-09 11:30 UTC, flyingsilverfin commented on concept/type/impl/ThingTypeImpl.java
> +        public static int compareAnnotationsPermissive(Set<TypeQLToken.Annotation> first, Set<TypeQLToken.Annotation> second) {
Make two boolean methods:
```
        public static boolean isFirstStricter(Set<TypeQLToken.Annotation> first, Set<TypeQLToken.Annotation> second) {

        }

        public static boolean isFirstStrictOrEqual(Set<TypeQLToken.Annotation> first, Set<TypeQLToken.Annotation> second) {

        }

```

2024-02-13 10:21 UTC, flyingsilverfin commented on concept/type/impl/ThingTypeImpl.java
> +        }
let's put this in `validateAdd`

2024-02-13 10:21 UTC, flyingsilverfin commented on concept/type/impl/ThingTypeImpl.java
> +        DeclarationValidation.Owns.validateAdd(this, attributeType, annotations).forEach(e -> { throw exception(e); });
Let's just throw the first one explicitly

2024-02-14 17:13 UTC, flyingsilverfin commented on concept/validation/SubtypeValidation.java
> +                Arrays.stream(validationErrors).flatMap(Collection::stream).map(TypeDBException::getMessage)
formatting's a bit funny here?

2024-02-14 17:13 UTC, flyingsilverfin approved these changes

2024-02-16 17:21 UTC, krishnangovindraj commented on concept/validation/SubtypeValidation.java
> +                Arrays.stream(validationErrors).flatMap(Collection::stream).map(TypeDBException::getMessage)
Looks ok to me?

2024-03-07 09:29 UTC, merged