Allow Type IDs of deleted types to be reused
vaticle/typedb pull request #7040
Opened 2024-04-15 16:34 UTC by krishnangovindraj

(DRAFT, because this is based off the Arc changes)

## Usage and product changes
Changes how type IDs are allocated so Type IDs from deleted types can be reused and allocated to newly created types.

## Implementation
* Instead of just incrementing an AtomicU16, we iterate over the `zip(range_of_type_ids, type_ids_in_db)` ids and return the first "gap" ( `it.0 != it.1` )
* We store an offset to start the next iteration from, so that we do a maximum of two seeks for allocating multiple Type IDs.
* If we don't find a free TypeID from our offset, we do another scan from the beginning (offset  = 0)

2024-04-16 13:12 UTC, krishnangovindraj reviewed
Self review

2024-04-16 13:12 UTC, krishnangovindraj commented on encoding/graph/type_/vertex_generator.rs
> +        build_vertex_role_type, TypeID, TypeVertex,
These are currently generated by macros, though they could likely be const instances of a struct.

```rust
pub struct TypeVertexConstructor {
    prefix : Prefix
}

impl TypeVertexConstructor {
    pub fn new_vertex(&self, bytes: Bytes<'_, BUFFER_KEY_INLINE>) -> TypeVertex<'_> {
        let vertex = TypeVertex::new(bytes);
        debug_assert_eq!(vertex.prefix(), self.prefix);
        vertex
    }

    pub fn build_vertex(&self, type_id: TypeID) -> TypeVertex<'static> {
        TypeVertex::build(self.prefix.prefix_id(), type_id)
    }

    pub fn build_prefix(&self) -> StorageKey<'static, { TypeVertex::LENGTH_PREFIX }> {
        StorageKey::new_ref(TypeVertex::KEYSPACE, ByteReference::new(&self.prefix.prefix_id().bytes))
    }

    pub fn is_same_kind(&self, bytes: Bytes<'_, BUFFER_KEY_INLINE>) -> bool {
        bytes.length() == TypeVertex::LENGTH && TypeVertex::new(bytes).prefix() == self.prefix
    }
}

const ENTITY_TYPE_CONSTRUCTOR : TypeVertexConstructor = TypeVertexConstructor { prefix: Prefix::VertexEntityType };
const RELATION_TYPE_CONSTRUCTOR : TypeVertexConstructor = TypeVertexConstructor { prefix: Prefix::VertexRelationType };
const ATTRIBUTE_TYPE_CONSTRUCTOR : TypeVertexConstructor = TypeVertexConstructor { prefix: Prefix::VertexAttributeType };
const ROLE_TYPE_CONSTRUCTOR : TypeVertexConstructor = TypeVertexConstructor { prefix: Prefix::VertexRoleType };
```

2024-04-16 13:12 UTC, krishnangovindraj commented on encoding/graph/type_/vertex_generator.rs
> +    to_vertex:  fn (TypeID) -> TypeVertex<'static>
The fn could be replaced by the struct reference above if needed.
The root type could also be stored in the struct instead.

2024-04-16 13:12 UTC, krishnangovindraj commented on encoding/tests/test_type_vertex.rs
> +// TODO: Update all tests with higher level APIs
TODO? Or just move the thing id's reset test out?

2024-04-16 14:16 UTC, flyingsilverfin requested changes

2024-04-16 18:00 UTC, krishnangovindraj commented on encoding/tests/test_type_vertex.rs
> +// TODO: Update all tests with higher level APIs
We decided we're not bothering to reset the thing ID.

2024-04-17 08:49 UTC, krishnangovindraj commented on encoding/graph/type_/vertex_generator.rs
> +        build_vertex_role_type, TypeID, TypeVertex,
Added a todo in the code to do it.

2024-04-17 09:20 UTC, flyingsilverfin approved these changes

2024-04-17 10:09 UTC, merged